### ISSUE TITLE
The histogram is empty, please file a bug report.

### ISSUE THREAD

**Issue by Tuanzhang911** [pankajmishra000/VT-ADL#11]
after  175  epoch，there raise  a wrong .

![image](https://user-images.githubusercontent.com/64623625/207024108-74c63258-3f8a-496c-b2d2-4bd61a7b3727.png)

The parameters are set by default,,,,hazelnut

**Comment by SushantGautam** [comment]
Same issue!!

**Comment by pankajmishra000** [comment]
check the number of Gaussians
