### ISSUE TITLE
Train.py Problems

### ISSUE THREAD

**Issue by Enverrrr** [pankajmishra000/VT-ADL#13]
Hey,
I downloaded dataset and change dataset directory in mvtech.py but when i run ```python3 train.py -p 3``` it returns 
train_normal_image = torch.stack([T(load_images(j,i)) for j in train_path_images.keys() for i in train_path_images[j]])
AttributeError: 'NoneType' object has no attribute 'keys'
this one. How can i solve that problem.

**Comment by LrsThn** [comment]
The folders of all the different classes (hazelnut etc.) must be situated in the same directory. If the folder where all the different class folders are situated is called "mvtec_dataset" (as an example) you must set the dataset directory in mvtech.py to the "mvtec_dataset" folder and not the "hazelnut" folder directly.

**Comment by pankajmishra000** [comment]
solved by the last comment.
