### ISSUE TITLE
NameError: name 'thres' is not defined

### ISSUE THREAD

**Issue by leolin65** [pankajmishra000/VT-ADL#2]
Could you help to resolve, thank you.

Traceback (most recent call last):
  File "test.py", line 113, in <module>
    def Patch_Overlap_Score(data_load = loader[1:], threshold = thres, upsample =1):
NameError: name 'thres' is not defined

**Comment by leolin65** [comment]
my environment.  torch=1.9.0

**Comment by pankajmishra000** [comment]
updated the test file. It was a minor argument pass error. Now I fixed it. Get the recent clone. thanks
