### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by nitinsharanarthi** [pankajmishra000/VT-ADL#5]
Hey Pankaj, 

Excellent repository!!! 

Could you upload a script to fine-tune/train on custom dataset?

Much appreciated. 

Thanks and regards

**Comment by pankajmishra000** [comment]
Hi,
no trained model is uploaded due to commercial rights related to the project. Custom data set training can be done in the same way, as it is done for the MVTec. Have a look at the MVTec.py file and train.py file.

If you still have any specific problems, I will be happy to help.
thanks
