### ISSUE TITLE
Bad results but high scores

### ISSUE THREAD

**Issue by Y-JIE-CREATOR** [pankajmishra000/VT-ADL#9]
Hi Pankaj!
     As for 'hazelnut'
     I've correctly set all the training hyperparameters (epochs = 400, No. of Gaussians =150, LR=0.00008 #4 ). And the test scores look good. 
              (
              PRO Score: 0.9412769221998033
              AUC Total: 0.765357142857143
              PR_AUC Total: 0.8664612457384442
              )
     However, the heatmap of the result looks terrible. Could you tell me the reason? If I set something wrong?

**Comment by pankajmishra000** [comment]
Maybe some plotting error. Check over there. Or might be something else. You gotta dig down in the plotting side.

**Comment by kashiani** [comment]
@Y-JIE-CREATER 
Did you solve the issue with the heatmap illustrations?
